createAviso:
  handler: src/handlers/avisos/createAviso.execute
  environment:
    FIREBASE_SERVICE_ACCOUNT: ${self:custom.environment.FIREBASE_SERVICE_ACCOUNT}
  iamRoleStatementsInherit: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ssm:GetParameter
      Resource:
        - ${self:custom.ssmParameterArn}/firebase_service_account
        - ${self:custom.ssmParameterArn}/*/firebase_service_account
  events:
    - httpApi:
        method: POST
        path: /v1/avisos
        authorizer:
          name: cognitoAuthorizer

listAvisos:
  handler: src/handlers/avisos/listAvisos.execute
  events:
    - httpApi:
        method: GET
        path: /v1/avisos
        authorizer:
          name: cognitoAuthorizer

updateAviso:
  handler: src/handlers/avisos/updateAviso.execute
  events:
    - httpApi:
        method: PUT
        path: /v1/avisos/{id}
        authorizer:
          name: cognitoAuthorizer

removeAviso:
  handler: src/handlers/avisos/removeAviso.execute
  events:
    - httpApi:
        method: DELETE
        path: /v1/avisos/{id}
        authorizer:
          name: cognitoAuthorizer
