gerarMensalidades:
  handler: src/handlers/mensalidades/gerarMensalidades.execute
  iamRoleStatementsInherit: true
  iamRoleStatements: ${self:custom.encryptionKeyIamStatements}
  events:
    - schedule: cron(0 6 1 * ? *)

gerarMensalidadesAno:
  handler: src/handlers/mensalidades/gerarMensalidadesAno.execute
  timeout: 120
  iamRoleStatementsInherit: true
  iamRoleStatements: ${self:custom.encryptionKeyIamStatements}
  events:
    - schedule: cron(0 3 1 1 ? *)

listMensalidades:
  handler: src/handlers/mensalidades/listMensalidades.execute
  iamRoleStatementsInherit: true
  iamRoleStatements: ${self:custom.encryptionKeyIamStatements}
  events:
    - httpApi:
        method: GET
        path: /v1/mensalidades
        authorizer:
          name: cognitoAuthorizer
