createDespesa:
  handler: src/handlers/despesas/createDespesa.execute
  events:
    - httpApi:
        method: POST
        path: /v1/despesas
        authorizer:
          name: cognitoAuthorizer

listDespesas:
  handler: src/handlers/despesas/listDespesas.execute
  events:
    - httpApi:
        method: GET
        path: /v1/despesas
        authorizer:
          name: cognitoAuthorizer

updateDespesa:
  handler: src/handlers/despesas/updateDespesa.execute
  events:
    - httpApi:
        method: PUT
        path: /v1/despesas/{id}
        authorizer:
          name: cognitoAuthorizer

removeDespesa:
  handler: src/handlers/despesas/removeDespesa.execute
  events:
    - httpApi:
        method: DELETE
        path: /v1/despesas/{id}
        authorizer:
          name: cognitoAuthorizer
