createAgenda:
  handler: src/handlers/agendas/createAgenda.execute
  iamRoleStatementsInherit: true
  iamRoleStatements: ${self:custom.encryptionKeyIamStatements}
  events:
    - httpApi:
        method: POST
        path: /v1/agenda
        authorizer:
          name: cognitoAuthorizer

updateAgenda:
  handler: src/handlers/agendas/updateAgenda.execute
  iamRoleStatementsInherit: true
  iamRoleStatements: ${self:custom.encryptionKeyIamStatements}
  events:
    - httpApi:
        method: PUT
        path: /v1/agenda/{id}
        authorizer:
          name: cognitoAuthorizer

removeAgenda:
  handler: src/handlers/agendas/removeAgenda.execute
  iamRoleStatementsInherit: true
  iamRoleStatements: ${self:custom.encryptionKeyIamStatements}
  events:
    - httpApi:
        method: DELETE
        path: /v1/agenda/{id}
        authorizer:
          name: cognitoAuthorizer

getAgenda:
  handler: src/handlers/agendas/getAgenda.execute
  iamRoleStatementsInherit: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
      Resource:
        - ${self:custom.fotosObjectArn}
    - Effect: Allow
      Action:
        - ssm:GetParameter
      Resource:
        - ${self:custom.ssmParameterArn}/encryption_key
        - ${self:custom.ssmParameterArn}/*/encryption_key
  events:
    - httpApi:
        method: GET
        path: /v1/agenda
        authorizer:
          name: cognitoAuthorizer

getHistoricoAgenda:
  handler: src/handlers/agendas/getHistoricoAgenda.execute
  iamRoleStatementsInherit: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
      Resource:
        - ${self:custom.fotosObjectArn}
    - Effect: Allow
      Action:
        - ssm:GetParameter
      Resource:
        - ${self:custom.ssmParameterArn}/encryption_key
        - ${self:custom.ssmParameterArn}/*/encryption_key
  events:
    - httpApi:
        method: GET
        path: /v1/agenda/historico
        authorizer:
          name: cognitoAuthorizer

removerAgendasAnoAnterior:
  handler: src/handlers/agendas/removerAgendasAnoAnterior.execute
  events:
    - schedule:
        rate: cron(0 3 1 1 ? *)

enviarAgenda:
  handler: src/handlers/agendas/enviarAgenda.execute
  environment:
    FIREBASE_SERVICE_ACCOUNT: ${self:custom.environment.FIREBASE_SERVICE_ACCOUNT}
  iamRoleStatementsInherit: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ssm:GetParameter
      Resource:
        - ${self:custom.ssmParameterArn}/firebase_service_account
        - ${self:custom.ssmParameterArn}/*/firebase_service_account
        - ${self:custom.ssmParameterArn}/encryption_key
        - ${self:custom.ssmParameterArn}/*/encryption_key
  events:
    - httpApi:
        method: POST
        path: /v1/agenda/{id}/enviar
        authorizer:
          name: cognitoAuthorizer
